version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: cinetanger_postgres
    ports:
      - "54321:5432"   # â›” exposed DB
    environment:
      POSTGRES_DB: cinetanger_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cinetanger_net

  api:
    build: ./backend
    container_name: cinetanger_api
    ports:
      - "80:3000"     
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 3000

      DB_HOST: postgres   # internal Docker communication
      DB_PORT: 54321
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: cinetanger_db

      JWT_SECRET: votre_super_secret_jwt_cinema_2024
      JWT_EXPIRE: 7d
    networks:
      - cinetanger_net

volumes:
  pgdata:

networks:
  cinetanger_net:
    driver: bridge
